# Generated by Django 3.1.7 on 2021-02-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
