# Generated by Django 3.1.7 on 2021-02-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0002_auto_20210222_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Image',
        ),
    ]
