# Generated by Django 3.1.7 on 2021-02-23 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0004_auto_20210223_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=100, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='product_name')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fileApp.category', verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='item_name')),
                ('size', models.CharField(max_length=4, verbose_name='size')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='fileApp.product', verbose_name='item')),
            ],
        ),
    ]
