# Generated by Django 3.1.7 on 2021-02-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0005_category_item_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
    ]
