# Generated by Django 3.1.7 on 2021-02-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0007_auto_20210223_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=4, verbose_name='size')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='fileApp.product', verbose_name='item')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
