# Generated by Django 3.1.6 on 2021-02-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileApp', '0008_auto_20210223_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category',
        ),
    ]
